# Analysis results, readme and runfolder/runfolders.
#Input: PROJECTID
variables:
  rootpath: "/proj/ngi2016001/nobackup/NGI"
  runfolderpath: "/proj/ngi2016001/incoming"
  analysispath: "{rootpath}/ANALYSIS/{projectid}"
  deliverypath: "{rootpath}/DELIVERY/{projectid}"
files_to_organise:
- source: "{analysispath}/results"
  destination: "{deliverypath}/results"
  options: 
    required: True
    link_type: "softlink" 
- source: "{deliverypath}/softlinks/DELIVERY.README.RNASEQ.md"
  destination: "{deliverypath}/DELIVERY.README.RNASEQ.md"
  options: 
    required: True
    link_type: "softlink"
- source: "{runfolderpath}/*/Projects/{projectid}"
  destination: "{deliverypath}/fastq/"
  options: 
    required: True
    link_type: "softlink"
