# Analysis results, readme and runfolder/runfolders.
#Input: PROJECTID
rootpath: "/proj/ngi2016001/nobackup/NGI"
runfolderpath: "/proj/ngi2016001/incoming"
analysispath: "{rootpath}/ANALYSIS/{projectid}"
deliverypath: "{rootpath}/DELIVERY/{projectid}"
files_to_deliver:
- source: "{analysispath}/results"
  destination: "{deliverypath}/results"
  options: 
    required: True
    symlink: True 
- source: "{deliverypath}/softlinks/DELIVERY.README.RNASEQ.md"
  destination: "{deliverypath}/DELIVERY.README.RNASEQ.md"
  options: 
    required: True
    symlink: True
- source: "{runfolderpath}/*/Projects/{projectid}"
  destination: "{deliverypath}/fastq/"
  options: 
    required: True
    symlink: True
