"""Table for NGI-status

Revision ID: ee22356628a1
Revises: ea812cd3ab7b
Create Date: 2018-02-21 10:36:04.858610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee22356628a1'
down_revision = 'ea812cd3ab7b'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngi_status',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_project', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'successful', 'failed', name='ngistatusasenum'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ngi_status')
    ### end Alembic commands ###
